language: node_js
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - dpkg
      - google-chrome-stable
node_js:
  - "12.18.2"

jobs:
  include:
    - stage: Test, Unit, Lint, Coverage
      script:
        - npm install
        - npm run lint
        - npm run prekarma
        - npm run ng-test-headless
        - npm run ng-test-headless-coverage

    - stage: Deploy, Firebase serverless architecture
      if: branch = master
      script:
        - echo "Building"
        - npm install
        - npm run build
        - echo "Deploying"
      install:
        - npm install -g firebase-tools
      after-success:
        - firebase deploy --token $FIREBASE_TOKEN
