language: node_js
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - dpkg
      - google-chrome-stable
node_js:
  - "12.18.2"
script:
  - npm install
  - echo "Testing"
  - npm run prekarma
  - npm run ng-test-headless
  # - npm run coverage
  - echo "Building"
  - npm run build
  - echo "Deploying"
install:
  - npm install -g firebase-tools
after-success:
  - firebase deploy --token $FIREBASE_TOKEN
