language: node_js
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - dpkg
      - google-chrome-stable
node_js:
  - "12.18.2"
script:
  - npm install
  - echo "Testing"
  - npm run pree2e
  - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
  - npm run test
  - npm run coverage
  - echo "Building"
  - npm run build
  - echo "Deploying"
install:
  - npm install -g firebase-tools
after-success:
  - firebase deploy --token $FIREBASE_TOKEN
