language: node_js
node_js:
  - "12.18.2"
script:
  - npm install
  - echo "Testing"
  - npm run test
  - npm run coverage
  - echo "Building"
  - npm run build
  - echo "Deploying"
install:
  - npm install -g firebase-tools
after-success:
  - firebase deploy --token $FIREBASE_TOKEN
